// twitch scopes
export const TWITCH_SCOPES = [
  "openid",
  "user:read:email",
  "user:read:follows",
  "user:bot",
  "user:read:chat",
  "user:read:broadcast",
  "user:write:chat",
  "user:edit",
  "moderator:manage:shoutouts",
  "moderator:manage:shield_mode",
  "moderator:read:followers",
  "moderator:read:chatters",
  "moderator:manage:automod_settings",
  "moderator:manage:banned_users",
  "channel:read:subscriptions",
  "channel:manage:redemptions",
  "channel:manage:raids",
  "channel:manage:polls",
  "channel:read:hype_train",
  "channel:manage:broadcast",
  "channel:manage:ads",
  "bits:read",
  "channel:manage:polls",
  "editor:manage:clips",
  "channel:manage:clips",
  "channel:bot",
];

export const discordInviteLink = "https://discord.gg/29Eq659egv";
